name: tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    name: '✅ cypress'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'electron']
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v4

      - name: Install Google Fonts
        run: |
          wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip
          unzip NotoSansCJKjp-hinted.zip -d NotoSansCJKjp
          mv NotoSansCJKjp /usr/share/fonts/
          fc-cache -fv

      - name: '✅ Run Cypress'
        if: ${{ !env.ACT }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}

      - name: '☁️ Archive artifacts'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.browser }}
          path: |
            logs
